POST http://localhost:8080/attach/upload/product?productId=8a8a839d81be32510181be368e710002
Content-Type: multipart/form-data; boundary=WebAppBoundary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY3ODYzMjIsImV4cCI6MTY1Njg3MjcyMiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.XdrgQu_P7mRqc5aoNhjKguXyVXhKqve1vDpzeaTFFzI

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="p1.jfif"

< C:\Users\user\Desktop\p1.jfif

###
GET http://localhost:8080/attach/open?fileId=4028abcd8185de72018185e268460000

###

DELETE http://localhost:8080/attach/deleted?fileId=4028abcd8185de72018185e268460000

###

GET http://localhost:8080/attach/pagination?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYwNTg1NTUsImV4cCI6MTY1NjE0NDk1NSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiQURNSU4ifQ.geD57-Yuxxx3-eghRb_RcY0H604CuFwuY4H2RwXifWM
